"""
Handoff brief: what the agents did in a repository, what is still broken and
what is in flight, as Markdown to paste into a fresh agent session (or to
switch agents mid-task) so the next one does not start from zero.
"""

from __future__ import annotations

import os
import time
from collections import Counter
from typing import Any, Dict, List, Optional

from . import ui
from .gitcore import GitError, Repo
from .state import State


def _when(ts: float) -> str:
    return time.strftime("%b %d %H:%M", time.localtime(ts))


def build(repo: Repo, state: State, sessions: Optional[List[Any]] = None, days: int = 7) -> str:
    lines: List[str] = [f"# Handoff brief: {repo.name} ({repo.branch_display()})", "",
                        f"_Generated by gitnolo {_when(time.time())}. Paste this into the next agent session._", ""]

    same = [s for s in (sessions or []) if s.repo and os.path.realpath(s.repo) == os.path.realpath(repo.root)]
    if same:
        lines += ["## Recent agent sessions", ""]
        for s in sorted(same, key=lambda s: -s.updated)[:6]:
            why = f", {s.stop_reason}" if s.stop_reason and s.stop_reason != "completed" else ""
            lines.append(f"- **{s.agent}**: {s.title or 'untitled task'} ({s.state}{why}, {ui.ago(s.updated)} ago)")
        last = next((s for s in sorted(same, key=lambda s: -s.updated) if s.final_message), None)
        if last:
            report = last.final_message.strip()
            if len(report) > 1500:
                report = report[:1500].rsplit("\n", 1)[0] + "\n…"
            lines += ["", f"### Last report from {last.agent}", "", report]
        lines.append("")

    runs = [h for h in state.history(200) if os.path.realpath(h.get("repo", "")) == os.path.realpath(repo.root)
            and time.time() - h.get("t", 0) < days * 86400]
    if runs:
        lines += ["## Shipped by gitnolo", ""]
        for h in runs[-8:][::-1]:
            pr = h.get("pr") or ""
            num = pr.rsplit("/", 1)[-1] if pr else ""
            lines.append(f"- {_when(h['t'])} {h.get('agent') or 'manual'}: {h.get('commits', 0)} commits"
                         + (f", PR #{num} {'merged' if h.get('merged') else 'open'}" if num else ""))
        lines.append("")

    open_issues = state.open_ledger(repo.root)
    if open_issues:
        lines += ["## Known open problems", ""]
        for e in open_issues[:12]:
            ref = f"#{e['number']} " if e.get("number") else ""
            lines.append(f"- {ref}{e['title']} (reported by {e.get('agent') or 'agent'}, {ui.ago(e.get('t'))} ago)")
        lines.append("")
    fixed = [e for e in state.ledger(repo.root) if e.get("status") in ("closed", "resolved", "closing")
             and time.time() - e.get("resolved_at", e.get("t", 0)) < days * 86400]
    if fixed:
        lines += ["## Recently fixed", ""] + [f"- {e['title']}" for e in fixed[-6:][::-1]] + [""]

    try:
        changes = repo.changes()
        if changes:
            lines += ["## Uncommitted right now", ""]
            lines += [f"- `{c.path}` ({c.kind})" for c in changes[:15]]
            if len(changes) > 15:
                lines.append(f"- and {len(changes) - 15} more")
            lines.append("")
        out = repo.run("log", f"--since={days} days ago", "--name-only", "--format=", "-n", "400", check=False)
        hot = Counter(p for p in out.splitlines() if p.strip()).most_common(8)
        if hot:
            lines += [f"## Most changed files (last {days} days)", ""] + [f"- `{p}` ({n})" for p, n in hot] + [""]
    except GitError:
        pass

    branch = state.open_branch(repo.root)
    if branch:
        lines += ["## In flight", "", f"- branch `{branch.get('branch')}`" + (f", PR #{branch['pr']}" if branch.get("pr") else "")
                  + " is open; gitnolo will keep adding to it.", ""]
    return "\n".join(lines).rstrip() + "\n"
