"""
Build edition. The personal build is unrestricted; the community build
(generated by scripts/build_community.py) only works on public repositories
and writes at most COMMUNITY_MAX_COMMITS commits per change.
"""

EDITION = "community"
COMMUNITY_MAX_COMMITS = 15


def is_community() -> bool:
    return EDITION == "community"
